name:                haskell-rest
version:             0.1.0.0
github:              "fleurnoir/haskell-rest"
license:             BSD3
author:              "Andrei Miasnikov"
maintainer:          "myasnikov.nd@gmail.com"
copyright:           "2022 Andrei Miasnikov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fleurnoir/haskell-rest#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- http-conduit
- aeson
- text
- mtl
- either
#- Spock
- resource-pool
- happstack-server
- monad-logger
- persistent
- persistent-sqlite
- persistent-template
- base64-bytestring

library:
  source-dirs: src

executables:
  haskell-rest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-rest
    

tests:
  haskell-rest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-rest

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
